/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rifal
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
    }
    
    int xx, xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeForm = new javax.swing.JButton();
        btn_psn_wedd = new javax.swing.JButton();
        btn_psn_prewed = new javax.swing.JButton();
        btn_psn_engagement = new javax.swing.JButton();
        btn_kontak = new javax.swing.JLabel();
        btn_portofolio = new javax.swing.JLabel();
        btn_tentangKami = new javax.swing.JLabel();
        btn_review = new javax.swing.JLabel();
        btn_availabe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeForm.setText("X");
        closeForm.setBorder(null);
        closeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormActionPerformed(evt);
            }
        });
        getContentPane().add(closeForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 30, 30));

        btn_psn_wedd.setBackground(new java.awt.Color(247, 240, 216));
        btn_psn_wedd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_psn_wedd.setText("BOOKING NOW");
        btn_psn_wedd.setBorder(null);
        btn_psn_wedd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_psn_weddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_psn_wedd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 190, 70));

        btn_psn_prewed.setBackground(new java.awt.Color(247, 240, 216));
        btn_psn_prewed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_psn_prewed.setText("BOOKING NOW");
        btn_psn_prewed.setBorder(null);
        btn_psn_prewed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_psn_prewedActionPerformed(evt);
            }
        });
        getContentPane().add(btn_psn_prewed, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 190, 70));

        btn_psn_engagement.setBackground(new java.awt.Color(247, 240, 216));
        btn_psn_engagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_psn_engagement.setText("BOOKING NOW");
        btn_psn_engagement.setBorder(null);
        btn_psn_engagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_psn_engagementActionPerformed(evt);
            }
        });
        getContentPane().add(btn_psn_engagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 190, 70));

        btn_kontak.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btn_kontak.setForeground(new java.awt.Color(247, 240, 216));
        btn_kontak.setText("Kontak");
        btn_kontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kontakMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        btn_portofolio.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btn_portofolio.setForeground(new java.awt.Color(247, 240, 216));
        btn_portofolio.setText("Portofolio");
        btn_portofolio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_portofolioMouseClicked(evt);
            }
        });
        getContentPane().add(btn_portofolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        btn_tentangKami.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btn_tentangKami.setForeground(new java.awt.Color(247, 240, 216));
        btn_tentangKami.setText("Tentang Kami");
        btn_tentangKami.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tentangKamiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tentangKami, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        btn_review.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btn_review.setForeground(new java.awt.Color(246, 239, 215));
        btn_review.setText("Review");
        btn_review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reviewMouseClicked(evt);
            }
        });
        getContentPane().add(btn_review, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        btn_availabe.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btn_availabe.setForeground(new java.awt.Color(246, 239, 215));
        btn_availabe.setText("Schedule");
        btn_availabe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_availabeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_availabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/homePage.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormActionPerformed
        dispose();
    }//GEN-LAST:event_closeFormActionPerformed

    private void btn_psn_weddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_psn_weddActionPerformed
        weddingPage WP = new weddingPage();
        WP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_psn_weddActionPerformed

    private void btn_psn_engagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_psn_engagementActionPerformed
        engagement engage = new engagement();
        engage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_psn_engagementActionPerformed

    private void btn_portofolioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_portofolioMouseClicked
        portofolio porto = new portofolio();
        porto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_portofolioMouseClicked

    private void btn_tentangKamiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tentangKamiMouseClicked
        TentangKami aboutUs = new TentangKami();
        aboutUs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_tentangKamiMouseClicked

    private void btn_psn_prewedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_psn_prewedActionPerformed
        prewedding PW = new prewedding();
        PW.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_psn_prewedActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void btn_kontakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kontakMouseClicked
        kontak contact = new kontak();
        contact.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kontakMouseClicked

    private void btn_availabeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_availabeMouseClicked
        Schedule schedule = new Schedule();
        schedule.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_availabeMouseClicked

    private void btn_reviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reviewMouseClicked
        review Review = new review();
        Review.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_reviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_availabe;
    private javax.swing.JLabel btn_kontak;
    private javax.swing.JLabel btn_portofolio;
    private javax.swing.JButton btn_psn_engagement;
    private javax.swing.JButton btn_psn_prewed;
    private javax.swing.JButton btn_psn_wedd;
    private javax.swing.JLabel btn_review;
    private javax.swing.JLabel btn_tentangKami;
    private javax.swing.JButton closeForm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
