/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rifal
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;

public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    
    int xx,xy;
    
    public loginForm() {
        initComponents();
        
        btn_signIn.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        txt_int_email = new javax.swing.JTextField();
        txt_int_pass = new javax.swing.JTextField();
        btn_signIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BuatAkun = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("X");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 20, 20));

        txt_int_email.setBackground(new java.awt.Color(82, 122, 130));
        txt_int_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_int_email.setText("Enter Email");
        txt_int_email.setBorder(null);
        txt_int_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_int_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_int_emailFocusLost(evt);
            }
        });
        txt_int_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_int_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_int_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 340, 40));

        txt_int_pass.setBackground(new java.awt.Color(82, 122, 130));
        txt_int_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_int_pass.setText("Enter Password");
        txt_int_pass.setBorder(null);
        txt_int_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_int_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_int_passFocusLost(evt);
            }
        });
        txt_int_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_int_passActionPerformed(evt);
            }
        });
        getContentPane().add(txt_int_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 340, 40));

        btn_signIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_signIn.setText("Sign In");
        btn_signIn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_signIn.setBorderPainted(false);
        btn_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signInActionPerformed(evt);
            }
        });
        btn_signIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_signInKeyPressed(evt);
            }
        });
        getContentPane().add(btn_signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 360, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Belum Punya akun? ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        BuatAkun.setText("buat akun");
        BuatAkun.setBorder(null);
        BuatAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuatAkunActionPerformed(evt);
            }
        });
        getContentPane().add(BuatAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 90, 20));

        jButton4.setText("<");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 20, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/LoginPage.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void txt_int_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_int_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_int_emailActionPerformed

    private void txt_int_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_int_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_int_passActionPerformed

    private void txt_int_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_int_emailFocusGained
        String email = txt_int_email.getText();
        if(email.equals("Enter Email")){
            txt_int_email.setText("");
        }
    }//GEN-LAST:event_txt_int_emailFocusGained

    private void txt_int_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_int_emailFocusLost
        String inEmail = txt_int_email.getText();
        if(inEmail.equals("") || inEmail.equals("Enter Email")){
            txt_int_email.setText("Enter Email");
        }
    }//GEN-LAST:event_txt_int_emailFocusLost

    private void txt_int_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_int_passFocusGained
        String pass = txt_int_pass.getText();
        if(pass.equals("Enter Password")){
            txt_int_pass.setText("");
        }
    }//GEN-LAST:event_txt_int_passFocusGained

    private void txt_int_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_int_passFocusLost
        String inPass = txt_int_pass.getText();
        if(inPass.equals("")||inPass.equals("Enter Password")){
            txt_int_pass.setText("Enter Password");
        }
    }//GEN-LAST:event_txt_int_passFocusLost

    private void BuatAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuatAkunActionPerformed
        createAccount buatAkun = new createAccount();
        buatAkun.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BuatAkunActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        welcomePage welcome = new welcomePage();
        welcome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signInActionPerformed
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        
        String enteredEmail = txt_int_email.getText();
        String enteredPassword = txt_int_pass.getText();
        
      
        try{
            // Mendapatkan koneksi dari kelas Koneksi
            connection = Koneksi.getKoneksi();
            
            // Query untuk memeriksa login
            String query = "SELECT * FROM users WHERE email = ? AND password = ?";
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, txt_int_email.getText());
            preparedStatement.setString(2, txt_int_pass.getText());
            
            resultSet = preparedStatement.executeQuery();
            
            if (checkLogin(enteredEmail, enteredPassword)){
                // Jika login berhasil
               homePage home = new homePage();
               home.setVisible(true);
               this.dispose();
            
            } else {
                // Jika login gagal
                loginForm login = new loginForm();
                login.setVisible(true);
                this.dispose();
            }
           
        }catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            //sumber daya tidak ditutup agar bisa digunakan kembali saat memasukan akun yg gagals
        }
    }//GEN-LAST:event_btn_signInActionPerformed

    private void btn_signInKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_signInKeyPressed

    }//GEN-LAST:event_btn_signInKeyPressed

    private boolean checkLogin(String email, String password){
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        
        try{
            connection = Koneksi.getKoneksi();
            String query = "SELECT * FROM users WHERE email = ? AND password = ?";
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, email);
            preparedStatement.setString(2, password);
            
            resultSet = preparedStatement.executeQuery();
            
            return resultSet.next();// True jika data ditemukan
        } catch (SQLException ex){
            ex.printStackTrace();
            return false;
        }finally {
        }
    }
    
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                welcomePage welcome = new welcomePage();
                welcome.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuatAkun;
    private javax.swing.JButton btn_signIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_int_email;
    private javax.swing.JTextField txt_int_pass;
    // End of variables declaration//GEN-END:variables
}
