/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rifal
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class myOrder extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public myOrder() {
        initComponents();
        populateComboBox();
    }
    
    int xx, xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeForm = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        txt_int_email = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox<>();
        btn_placeOrder = new javax.swing.JButton();
        txt_int_date = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeForm.setText("X");
        closeForm.setBorder(null);
        closeForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormActionPerformed(evt);
            }
        });
        getContentPane().add(closeForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 30, 30));

        btn_back.setText("<");
        btn_back.setBorder(null);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 30, 30));

        txt_int_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_int_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_int_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 360, 70));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 360, 70));

        btn_placeOrder.setBackground(new java.awt.Color(70, 105, 111));
        btn_placeOrder.setFont(new java.awt.Font("Montserrat Black", 0, 12)); // NOI18N
        btn_placeOrder.setForeground(new java.awt.Color(255, 255, 255));
        btn_placeOrder.setText("PLACE ORDER");
        btn_placeOrder.setToolTipText("");
        btn_placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_placeOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_placeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 250, 80));

        txt_int_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_int_dateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_int_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 360, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/myOrder.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1180, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormActionPerformed
        dispose();
    }//GEN-LAST:event_closeFormActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        homePage homepage = new homePage();
        homepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void txt_int_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_int_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_int_emailActionPerformed

    private void btn_placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_placeOrderActionPerformed
        String enterEmail = txt_int_email.getText();
        String enterDate = txt_int_date.getText();
        String enterType = jComboBox.getSelectedItem().toString();
        
        Connection connection = null;
        PreparedStatement preparedStatement = null;

        if (enterEmail.isEmpty() || enterType.isEmpty()) {
            return;
        }


        try {
            connection = Koneksi.getKoneksi(); // Assuming Koneksi is a class that provides a database connection

            String query = "INSERT INTO order_detail (email, product_name, date) VALUES (?,?,?)";

            preparedStatement = connection.prepareStatement(query);

            preparedStatement.setString(1, enterEmail);
            preparedStatement.setString(2, enterType);
            preparedStatement.setString(3, enterDate);
            
            

            preparedStatement.executeUpdate();


            // Optionally, show a success message or perform other actions
            System.out.println("Order placed successfully!");
            
            orderDetail OD = new orderDetail(enterEmail);
            OD.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            // Handle any database-related errors
            e.printStackTrace();
        } finally {
           
        }
    }//GEN-LAST:event_btn_placeOrderActionPerformed

    private void txt_int_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_int_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_int_dateActionPerformed
     
    private void populateComboBox() {
        try {
            Connection connection = Koneksi.getKoneksi(); // Assuming Koneksi is a class that provides a database connection

            String query = "SELECT product_name FROM product_list";

            try (PreparedStatement preparedStatement = connection.prepareStatement(query);
                 ResultSet resultSet = preparedStatement.executeQuery()) {
                jComboBox.removeAllItems();

                while (resultSet.next()) {
                    String productName = resultSet.getString("product_name");
                    jComboBox.addItem(productName);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_placeOrder;
    private javax.swing.JButton closeForm;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_int_date;
    private javax.swing.JTextField txt_int_email;
    // End of variables declaration//GEN-END:variables
}
